### ISSUE TITLE
Macro playing issue

### ISSUE THREAD

**Issue by rkkarnik** [yetanothergeek/fxite#9] opened 2015-01-14 22:33 UTC
I frequently run macros to edit lists that can vary from a few dozen rows to thousands. Mostly these are fairly simple such as taking a sequence of number on each line, and wrapping them in quotes and appending a comma - for example:

Before Macro
1234
5678
9012
3456
7890

After Macro
'1234',
'5678',
'9012',
'3456',
'7890',

Playing the macro for the lines that are visible within the window and do not require fxite to scroll the display works as it should.

However, once fxite starts to scroll the display to run the macro on other lines in the file, I frequently see this error:

![fxite_error](https://cloud.githubusercontent.com/assets/10538587/5749023/90bbc324-9bf9-11e4-9970-2be29318817e.jpg)

This happens when I just keep < CTRL > K pressed continuously. It does not happen if I took my fingers off the keys and pressed it independently each time. However, when I'm trying to apply the macro to several hundred lines, you can see why I'm not too keen to press the keys repeatedly.

**Comment by yetanothergeek** [comment] 2015-01-15 08:23
Hello rkkarink, 

Thanks to your clear description I was able to quickly reproduce the problem here.

And, if I comment out these two lines of code in `./src/cmd_utils.cpp` the problem seems to go away:

```C
    //    FXMessageBox::error(tw, MBOX_OK, _("Command error"),
    //      _("Multiple commands cannot be executed at the same time."));
```

In your situation I don't think that would be a problem, the editor will simply skip the extra keystroke and catch the next one, since the key is being held  down continuously anyway and the error message really is just an annoyance.

But there could be other situations where the error message is useful, maybe even critical, if some user-defined macro silently fails to execute because another one is busy.

It might even be possible to allow running multiple macros at the same time; I have considered experimenting with this, but it seems like that would just be asking for trouble, for instance if one macro closes a document at the same instant that another macro is modifying it, it could possibly crash the whole program.

I will try to dig deeper into this issue sometime in the next few days and hopefully come up with a solution can better deal with these different scenarios.

Thanks for the report!

**Comment by yetanothergeek** [comment] 2015-01-21 05:44
Should be fixed now with commit a062c40.

rkkarnik, are you able to build fxite from the git repo to test this fix? If not, please let me know what operating system you're using and I'll try to upload a fixed version for you to test.

**Comment by rkkarnik** [comment] 2015-01-21 15:24
Awesome! Unfortunately, I'm unable to build this myself. If you can upload one for me, that'd be great. I'm on Win 7/64 bit.

- raj

**Comment by yetanothergeek** [comment] 2015-01-22 05:45
Okay, here it is:
 http://jkp.nfshost.com/5AqCh/fxite-0.93-pre1-win32.zip
(It's actually 32-bit, but I guess that should work.)

**Comment by rkkarnik** [comment] 2015-01-22 21:51
Thanks for compiling! However... upon launching I get a Microsoft Visual C++ error - see attached:

![fxite_error](https://cloud.githubusercontent.com/assets/10538587/5865358/a8a2c4ca-a23d-11e4-8d3f-2cf37f48709f.jpg)

**Comment by rkkarnik** [comment] 2015-01-22 21:52
Err... wrong image :)

See below:

![fxite_error](https://cloud.githubusercontent.com/assets/10538587/5865380/dd0d0ca2-a23d-11e4-8f1e-ad59cda40d1a.jpg)

**Comment by yetanothergeek** [comment] 2015-01-23 03:45
OOPS... Sorry, guess I should have actually tried running it after it was built!

Should be fixed now:
  http://jkp.nfshost.com/5AqCh/fxite-0.93-pre2-win32.zip

**Comment by rkkarnik** [comment] 2015-01-23 18:08
Rock! It works like a charm!

Thank you, thank you!

**Comment by yetanothergeek** [comment] 2015-01-26 13:48
Glad to hear it worked. This change paves the way to solve some other problems, for instance there is currently a bug where "event hook" macros conflict with active shell commands. That seemed like a difficult problem to solve before, but it looks much easier now that I can see things from a slightly different angle. Thanks for the nudge!

**Comment by frusen** [comment] 2015-05-20 20:24
Should this be closed now?

**Comment by yetanothergeek** [comment] 2015-05-22 04:23
Yes, I think it should be closed. I had hoped to make an "official" binary release first, but the schedule keeps slipping for various reasons...
Thanks, @frusen!

**Closed by yetanothergeek** 2015-05-22 04:23 UTC
